name: e_comm
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

#================= PACKAGES ========================
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  get: ^4.6.5
  lottie: ^2.7.0
  shimmer: any
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.17.2
  firestore_model: any
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  cached_network_image: ^3.3.1


#=========================================
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
#=========================================
flutter:
  uses-material-design: true
#=========================================
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/images/lottie/
    - assets/images/products/
#=========================================
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-semiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 800

