// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnaGJwSvw32CWM3YTHidQd6Cjx9aUIiQ',
    appId: '1:782099304106:android:4cbb4e2de95f7cb9d48ad3',
    messagingSenderId: '782099304106',
    projectId: 'my-ecomm-b2452',
    storageBucket: 'my-ecomm-b2452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrexPwel2_vzOwyQ4q_RPsEtdnlbKOT50',
    appId: '1:782099304106:ios:d83ad80808912ea3d48ad3',
    messagingSenderId: '782099304106',
    projectId: 'my-ecomm-b2452',
    storageBucket: 'my-ecomm-b2452.appspot.com',
    androidClientId: '782099304106-50i6qtdgpd1f9hoe0g34d0c7i005iqub.apps.googleusercontent.com',
    iosClientId: '782099304106-v2tfr43mlrtrh0jirucd2jig8ot368fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComm',
  );

}